import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const tangoSans = localFont({
  src: "./fonts/TangoSans.ttf",
  variable: "--font-tango-sans",
  weight: "800",
});
const utendo = localFont({
  src: "./fonts/Utendo-Regular.ttf",
  variable: "--font-utendo",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${tangoSans.variable} ${utendo.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
